config/routes.rb
Rails.application.routes.draw do

  mount RailsAdmin::Engine => '/super_admin', as: 'rails_admin'

  devise_scope :user do
    root "devise/sessions#new"
    get '/logout' => 'devise/sessions#destroy'
  end

  get 'member', to: 'member#index'
  get 'admin', to: 'admin#index'
  get 'profile', to: 'users#show'

  devise_for :users, controllers: { invitations: 'users/invitations' }

  devise_scope :user do
    match "*path" => "devise/sessions#new", via: :all
    #match '*path' => redirect{ |p, req| req.flash[:notice] = "Error"; 'new_user_session_path' }, via: :get
  end

end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Projectx</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header class="navbar navbar-fixed-top navbar-inverse">
      <div class="container">
        <span id= "logo">Project X</span>
        <nav>
          <ul class="nav navbar-nav navbar-right">
           
            <% if user_signed_in? %>
                <li>
                  <% if current_user.admin? || current_user.super_admin? %>
                    <%= link_to "Home", admin_path %>
                  <% elsif current_user.member? %>
                    <%= link_to "Home", member_path %>
                  <% end %>
                </li>
                <li>
                    <%= link_to "Profile", profile_path %>
                </li>
                <li>
                    <%= link_to 'Logout', destroy_user_session_path, method: :delete %>
                </li>
              </li>
            <% else %>
              <li><%= link_to "Log in", new_user_session_path %></li>
            <% end %>
          </ul>
        </nav>
      </div>
    </header>

    <div class="container">
      
      <% if flash %>
        <% flash.each do |key, value| %>
          <%= content_tag :div, value, class: "flash #{key}" %>
        <% end %>
      <% end %>

      <% if user_signed_in? %>
          <% if current_user.admin? || current_user.super_admin? %>
            <h1>Admin's Page</h1>
          <% elsif current_user.member? %>
            <h1>Member's Page</h1>
          <% end %> 
      <% end %>

      <%= yield %>
 
    </div>


  </body>
</html>